services:
  - type: web
    name: tg-bot-schedule
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_TG_ID
        sync: false
      - key: PUBLIC_URL
        sync: false
